apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstar-sharp-aspnetcore
  template:
    metadata:
      labels:
        app: kstar-sharp-aspnetcore
    spec:
      containers:
      - name: kstar-sharp-aspnetcore
        image: "piotrkula.azurecr.io/ppumkin/kstar.sharp:latest" 
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /sqlite
          name: sqlite-db-volume
      volumes:
      - name: sqlite-db-volume
        hostPath:
          path: /home/sqlite
          type: Directory
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kstar-sharp-aspnetcore
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kstar-sharp-aspnetcore.local
      http:
        paths:
          - path: /
            backend:
              serviceName: kstar-sharp-aspnetcore
              servicePort: http
