apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstar-sharp-aspnetcore
  template:
    metadata:
      labels:
        app: kstar-sharp-aspnetcore
    spec:
      containers:
      - name: kstar-sharp-aspnetcore
        image: "piotrkula.azurecr.io/kstar.sharp.aspnetcore:37a56617f01630964c63f5be91e11d61f608dbbd"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /sqlite
          name: sqlite-db-volume
      volumes:
      - name: sqlite-db-volume
        hostPath:
          path: /home/k8admin/sqlite
          type: Directory
      imagePullSecrets:
        - name: regsecret
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kstar-sharp-console
  labels:
    app: kstar-sharp-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstar-sharp-console
  template:
    metadata:
      labels:
        app: kstar-sharp-console
    spec:
      containers:
      - name: kstar-sharp-console
        image: "piotrkula.azurecr.io/kstar.sharp.console:37a56617f01630964c63f5be91e11d61f608dbbd"
        args: ["--ip-192.168.1.50", "--sqlite-Data Source=/sqlite/inverter-data.db"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /sqlite
          name: sqlite-db-volume
      volumes:
      - name: sqlite-db-volume
        hostPath:
          path: /home/k8admin/sqlite
          type: Directory
      imagePullSecrets:
        - name: regsecret
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-kstar-console
spec:
  podSelector:
    matchLabels:
      app: kstar-sharp-console
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
---
apiVersion: v1
kind: Service
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kstar-sharp-aspnetcore
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kstar-sharp-aspnetcore
  labels:
    app: kstar-sharp-aspnetcore
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kstar-sharp-aspnetcore.local
      http:
        paths:
          - path: /
            backend:
              serviceName: kstar-sharp-aspnetcore
              servicePort: http
