name: "KStar Sharp - MQTT"
version: "latest"
slug: "kstar_sharp_mqtt"
description: "Collect KStar inverter data over WiFi IP and send to MQTT server - Works well with Home Assistant Energy Monitor"
url: "https://github.com/p10tyr/kstar.sharp"  
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
environment: {
  "IP": "192.168.1.18",
  "MQTT": "homeassistant",
  "SILENT": "true"
  }
privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
ingress: true
ports: {
   "8899/udp" : 8899
  }

host_network: true
full_access: true
# options:
#   IP: "192.168.1.1"
#   MQTT: "homeassistant"
#   SILENT: true
# schema:
#   IP: str
#   MQTT: str
#   SILENT: bool

image: "ghcr.io/p10tyr/kstar.sharp"