name: "KStar Sharp - MQTT"
version: "1.0.0"
slug: "kstar_sharp_mqtt"
description: "Collect KStar inverter data over WiFi IP and send to MQTT server - Works well with Home Assistant Energy Monitor"
url: "https://github.com/p10tyr/kstar.sharp"  
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/p10tyr/kstar.sharp"