name: "KStar Sharp - MQTT"
description: "Collect KStar inverter data over WiFi IP and send to MQTT server - Works well with Home Assistant Energy Monitor"
version: "1.0.0"
slug: "kstar_sharp_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386