name: "KStar Sharp - MQTT"
version: "latest"
slug: "kstar_sharp_mqtt"
description: "Collect KStar inverter data over WiFi IP and send to MQTT server - Works well with Home Assistant Energy Monitor"
url: "https://github.com/p10tyr/kstar.sharp"  
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
environment:
  --ip-: "192.168.1.18"
  --mqtt-: "homeassistant"
  --silent-: true
# options:
#   --ip-: "192.168.1.1"
#   --mqtt-: "homeassistant"
#   --silent-: true
# schema:
#   --ip-: str
#   --mqtt-: str
#   --silent-: bool

image: "ghcr.io/p10tyr/kstar.sharp"